<?php


namespace Teebb\CoreBundle\Doctrine\Types;


use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\Type;

class FieldDepartConfigurationType extends Type
{
    const FIELD_DEPART_CONFIGURATION_TYPE = 'depart';

    public function getSQLDeclaration(array $fieldDeclaration, AbstractPlatform $platform)
    {
        // TODO: Implement getSQLDeclaration() method.
        return 'depart';
    }

    public function convertToDatabaseValue($value, AbstractPlatform $platform)
    {

    }

    public function convertToPHPValue($value, AbstractPlatform $platform)
    {
        // TODO: Change the autogenerated stub
    }

    public function getName()
    {
        return self::FIELD_DEPART_CONFIGURATION_TYPE;
    }
}